"""Capability catalog for Benjamin agents."""

from __future__ import annotations

DEFAULT_AGENT_CAPABILITIES = {
    "research": {
        "description": "Research and current-news agent.",
        "responsibility": "Owns current-events research, source-backed answers, and date-specific synthesis.",
        "can_handle": ["news", "markets", "research", "fact_check", "current_events"],
        "tools_required": ["web"],
        "input_contract": {"message": "user request", "plan": "routing flags", "memory_context": "optional context"},
        "output_contract": {"status": "success|failed", "output": "source-backed answer", "notes": "provider trace"},
        "read_only": True,
        "write_capable": False,
    },
    "memory": {
        "description": "User memory agent.",
        "responsibility": "Owns durable memory recall, writes, deletes, and context shaping.",
        "can_handle": ["memory_read", "memory_write", "profile_recall"],
        "tools_required": ["memory_db"],
        "input_contract": {"message": "memory request", "plan": "memory write or recall"},
        "output_contract": {"status": "success|failed", "output": "memory result", "data": "memory action metadata"},
        "read_only": False,
        "write_capable": True,
    },
    "planning": {
        "description": "Task decomposition and structured planning.",
        "can_handle": ["planning", "decomposition", "architecture"],
        "tools_required": ["llm"],
        "read_only": True,
        "write_capable": False,
    },
    "execution": {
        "description": "General execution agent.",
        "can_handle": ["execution", "general_response", "drafting"],
        "tools_required": ["llm", "web_optional"],
        "read_only": False,
        "write_capable": True,
    },
    "verification": {
        "description": "Validation and revision agent.",
        "can_handle": ["verification", "qa", "code_review"],
        "tools_required": ["claude"],
        "read_only": True,
        "write_capable": False,
    },
    "code": {
        "description": "Code and architecture agent.",
        "responsibility": "Owns debugging, implementation guidance, refactors, and architecture judgment.",
        "can_handle": ["code", "debugging", "architecture", "refactor"],
        "tools_required": ["llm", "files"],
        "input_contract": {"message": "coding request", "plan": "verification flags", "memory_context": "project context"},
        "output_contract": {"status": "success|failed", "output": "code-focused answer", "notes": "provider trace"},
        "read_only": False,
        "write_capable": True,
    },
    "finance": {
        "description": "Markets and financial-analysis agent.",
        "responsibility": "Owns market, macro, and financial analysis with explicit freshness handling.",
        "can_handle": ["markets", "stocks", "macro", "finance_analysis"],
        "tools_required": ["web"],
        "input_contract": {"message": "finance question", "plan": "web-first routing"},
        "output_contract": {"status": "success|failed", "output": "current financial answer", "notes": "provider trace"},
        "read_only": True,
        "write_capable": False,
    },
    "assistant": {
        "description": "Personal assistant for tasks and organization.",
        "responsibility": "Owns chief-of-staff style organization, prioritization, and personal support.",
        "can_handle": ["personal_tasks", "scheduling", "organization", "reminders"],
        "tools_required": ["memory", "calendar", "llm"],
        "input_contract": {"message": "assistant request", "memory_context": "preferences and active projects"},
        "output_contract": {"status": "success|failed", "output": "operator-style answer", "notes": "provider trace"},
        "read_only": False,
        "write_capable": True,
    },
    "fitness_health": {
        "description": "Fitness, training, nutrition and body-optimization agent.",
        "responsibility": "Owns training, nutrition, recovery, and health routine guidance.",
        "can_handle": ["fitness", "nutrition", "training_program", "meal_plan", "health_routine"],
        "tools_required": ["all_tools"],
        "input_contract": {"message": "fitness request", "memory_context": "goals, routines, constraints"},
        "output_contract": {"status": "success|failed", "output": "practical health guidance", "notes": "provider trace"},
        "read_only": False,
        "write_capable": True,
    },
    "relationships": {
        "description": "Relationship dynamics, social situations, dating, communication, emotional analysis, and interpersonal strategy.",
        "responsibility": "Owns relationship judgment, messaging strategy, and interpersonal dynamics.",
        "can_handle": ["relationships", "dating", "social_dynamics", "communication", "emotional_analysis"],
        "tools_required": ["llm", "memory_db"],
        "input_contract": {"message": "relationship situation", "memory_context": "relevant personal context"},
        "output_contract": {"status": "success|failed", "output": "interpersonal guidance", "notes": "provider trace"},
        "read_only": False,
        "write_capable": True,
    },
    "business_strategy": {
        "description": "Business thinking, offers, positioning, GTM, monetization, growth strategy, and execution prioritization.",
        "responsibility": "Owns strategy calls, market framing, offer design, and prioritization.",
        "can_handle": ["business", "strategy", "pricing", "gtm", "growth", "monetization"],
        "tools_required": ["llm", "web", "files"],
        "input_contract": {"message": "business request", "memory_context": "projects and goals", "plan": "routing flags"},
        "output_contract": {"status": "success|failed", "output": "strategy recommendation", "notes": "provider trace"},
        "read_only": False,
        "write_capable": True,
    },
    "ai_expert": {
        "description": "AI, machine learning, language models, AI tools, model comparisons, AI product updates, and important AI news with practical explanation.",
        "responsibility": "Owns AI-model, tooling, and agent-system analysis with current-awareness when needed.",
        "can_handle": ["ai", "machine_learning", "llm", "models", "agents", "prompting", "ai_tools", "ai_news", "model_comparison"],
        "tools_required": ["llm", "web", "files", "memory_db"],
        "input_contract": {"message": "AI question", "plan": "routing flags", "memory_context": "user AI interests"},
        "output_contract": {"status": "success|failed", "output": "sharp practical AI answer", "notes": "provider trace"},
        "read_only": False,
        "write_capable": True,
    },
    "breaking": {
        "description": "Proactive breaking-alert pipeline.",
        "can_handle": ["alerts", "breaking_news"],
        "tools_required": ["web", "memory_db"],
        "read_only": True,
        "write_capable": False,
    },
    "priority": {
        "description": "Ranks proactive alerts.",
        "can_handle": ["ranking", "priority_scoring"],
        "tools_required": ["llm"],
        "read_only": True,
        "write_capable": False,
    },
    "quality": {
        "description": "Polishes outbound text.",
        "can_handle": ["polish", "rewrite"],
        "tools_required": ["llm"],
        "read_only": True,
        "write_capable": False,
    },
}
