"""Claude helpers with async wrappers for Benjamin."""
from __future__ import annotations

import asyncio
import os
import time

import anthropic

CLAUDE_MODEL = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-20250514")
MAX_RETRIES = 2
TIMEOUT_SECONDS = 30

_client = None


def get_client():
    global _client
    if _client is None:
        key = os.getenv("ANTHROPIC_API_KEY")
        if not key:
            raise ValueError("ANTHROPIC_API_KEY not set in .env")
        _client = anthropic.Anthropic(
            api_key=key,
            timeout=TIMEOUT_SECONDS,
            max_retries=MAX_RETRIES,
        )
    return _client


def _call_claude(prompt: str, *, max_tokens: int = 4096) -> str:
    client = get_client()
    start = time.time()
    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    latency_ms = int((time.time() - start) * 1000)
    print(f"Claude model used: {CLAUDE_MODEL} | latency: {latency_ms}ms")
    return (response.content[0].text if response.content else "").strip()


async def generate_claude_text(prompt: str, *, max_tokens: int = 4096) -> str:
    return await asyncio.to_thread(_call_claude, prompt, max_tokens=max_tokens)


async def review_and_improve_code(code_text: str, user_request: str) -> str:
    prompt = (
        f"Original user request:\n{user_request}\n\n"
        f"Draft code (generated by another model):\n```\n{code_text}\n```\n\n"
        "Review the draft code. Fix bugs, improve clarity and correctness. "
        "Return ONLY the final improved code with brief inline comments where needed. "
        "No extra explanation outside the code."
    )
    return await generate_claude_text(prompt)


async def sanity_check_answer(draft_answer: str, user_request: str, sources_text: str | None = None) -> str:
    sources_block = f"\n\nSources provided:\n{sources_text}" if sources_text else ""
    prompt = (
        f"Original user request:\n{user_request}\n\n"
        f"Draft answer (generated by another model):\n{draft_answer}{sources_block}\n\n"
        "You are a sanity/consistency checker. "
        "Verify factual accuracy, flag contradictions, and fix errors. "
        "Return the final corrected answer in the same language as the draft. "
        "If the draft is correct, return it as-is. "
        "No meta-commentary — only the final answer text."
    )
    return await generate_claude_text(prompt)
